// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CTCADASTROEMAILTICKETTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cTCADASTROEMAILTICKET() {
    driver.get("https://www.ticket.com.br/portal-usuario/login");
    driver.manage().window().setSize(new Dimension(683, 728));
    driver.findElement(By.cssSelector(".mobile-ap .link-acesso")).click();
    driver.findElement(By.cssSelector(".btn-login")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("nome"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("email"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("confirmarEmail"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("senha"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(1) > .invalido > div")).getText(), is("Por favor, digite seu nome"));
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(2) > .invalido > div")).getText(), is("Por favor, digite seu e-mail"));
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(3) > .invalido > div")).getText(), is("Por favor, confirme seu e-mail"));
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(4) > .invalido > div")).getText(), is("Por favor, digite uma senha"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".termos-azul"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-login"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".link"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("teste");
    driver.findElement(By.cssSelector(".background-pagina")).click();
    driver.findElement(By.cssSelector("path")).click();
    driver.findElement(By.cssSelector(".svg-inline--fa")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Filipe Muanis");
    driver.findElement(By.cssSelector(".background-pagina")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("filipemuanis@outlook.com");
    driver.findElement(By.cssSelector(".background-pagina")).click();
    driver.findElement(By.id("confirmarEmail")).click();
    driver.findElement(By.id("confirmarEmail")).sendKeys("filipemuanis@outlook.com");
    driver.findElement(By.cssSelector(".background-pagina")).click();
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.cssSelector(".background-pagina")).click();
    driver.findElement(By.id("senha")).sendKeys("teste123.");
    driver.findElement(By.cssSelector(".background-pagina")).click();
    driver.findElement(By.cssSelector(".btn-login")).click();
    assertThat(driver.findElement(By.cssSelector(".invalido > div")).getText(), is("Senha deve conter 6 a 10 caracteres com letras e números"));
    driver.findElement(By.cssSelector("path")).click();
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("teste...");
    driver.findElement(By.cssSelector(".invalido > div")).click();
    assertThat(driver.findElement(By.cssSelector(".invalido > div")).getText(), is("Senha deve conter 6 a 10 caracteres com letras e números"));
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("teste123");
    driver.findElement(By.cssSelector(".txt-acesse-seu-portal")).click();
    driver.findElement(By.cssSelector(".btn-login")).click();
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("tEste123");
    driver.findElement(By.cssSelector(".btn-login")).click();
    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("Tudo certo!\\\\nSua conta foi criada."));
    assertThat(driver.findElement(By.cssSelector(".txt-acesse-seu-portal > p")).getText(), is("Agora você pode entrar no portal Ticket com seus dados cadastrados."));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-recuperar"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".btn-recuperar")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("filipemuanis");
    driver.findElement(By.cssSelector(".background-pagina")).click();
    driver.findElement(By.cssSelector(".background-pagina")).click();
    driver.findElement(By.id("email")).sendKeys("filipemuanis@outlook.com");
    driver.findElement(By.cssSelector(".btn-login")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-login"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.id("email"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("senha"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".invalido > div")).getText(), is("Por favor, digite seu e-mail."));
    assertThat(driver.findElement(By.cssSelector(".invalid > div")).getText(), is("Por favor, digite sua senha"));
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("123456");
    driver.findElement(By.cssSelector(".mobile-ap > .acesso")).click();
    driver.findElement(By.cssSelector(".svg-inline--fa")).click();
    driver.findElement(By.cssSelector(".svg-inline--fa")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("filipemuanis@outlook.com");
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("tEste123");
    driver.findElement(By.cssSelector(".mobile-ap > .acesso")).click();
    driver.findElement(By.cssSelector(".svg-inline--fa")).click();
    driver.findElement(By.cssSelector(".btn-login")).click();
    driver.findElement(By.cssSelector(".abrir")).click();
    driver.findElement(By.cssSelector(".off:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".btn-login")).click();
  }
}
